name: Spell-check
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/spellcheck.yml@main
    permissions:
      contents: read
    with:
      ignore: abd,sme,tne
      skip: Rakefile,samples,source
